### ISSUE TITLE
Forward image attributes to `img` 

### ISSUE THREAD

**Issue by madeleineostoja** [alexstaroselsky/svelte-lazy-image#2]
It would be great if `svelte-lazy-image` either forwarded all props given to to the underlying `<img>` element (ie: `<img {...$$props} />`, or had props for all standard `img` attributes. Currently it's not possible to (for example) use responsive images with `sizes` and `srcset`.

Missing props:
- `srcset`
- `sizes`
- `width`
- `height`
- `loading`
- `class`

**Comment by alexstaroselsky** [comment]
@madeleineostoja That sounds like a good idea. I'll look to add that. Thanks for the suggestion.

**Comment by alexstaroselsky** [comment]
@madeleineostoja version 0.1.1 has been published that forwards attributes. Let me know if you have a chance to try it. Thanks!
