### ISSUE TITLE
Add typescript defs

### ISSUE THREAD

**Issue by madeleineostoja** [alexstaroselsky/svelte-lazy-image#3]
Would be great to have typescript definitions, now that Svelte has first class support for typescript

**Comment by alexstaroselsky** [comment]
TypeScript support would be a great feature. I'll look to add that. Thanks for the suggestion.

**Comment by alexstaroselsky** [comment]
@madeleineostoja TypeScript types have been added in version 0.2.0, let me know if you get a chance to try it out. Thanks!
