### ISSUE TITLE
This project does not have a licence [?]

### ISSUE THREAD

**Issue by GenieTim** [alexstaroselsky/svelte-lazy-image#7]
Hi dear maintainer,

it seems this project does not have an explicit licence. By default, this means that nobody would be allowed to use the project as it is your copyright. Would you mind adding one to make this explicit?

Best regards,

**Comment by alexstaroselsky** [comment]
Thank you for the suggestion. License has been added to `package.json` as well as a LICENSE file. Closing issue.
